### ISSUE TITLE
03-first-aws-environment component/terraform/static-site fails to deploy

### ISSUE THREAD

**Issue by jbouse** [cloudposse/tutorials#10]
## What
When following along through the tutorial and executing `atmos terraform deploy static-site --stack uw2-dev` files with the following error message:
```
Error: expected viewer_certificate.0.ssl_support_method to be one of [sni-only vip static-ip], got

  on .terraform/modules/cdn/main.tf line 272, in resource "aws_cloudfront_distribution" "default":
 272:     ssl_support_method             = var.acm_certificate_arn == "" ? "" : "sni-only"
```

## Why
I found on [main.tf#L3](https://github.com/cloudposse/tutorials/blob/f0d122e86d2e6d0756c7f9879d0d78b2577411fd/03-first-aws-environment/components/terraform/static-site/main.tf#L3) the `static-site` component is using v0.59.0 of the `cloudposse/cloudfront-s3-cdn/aws` module which passes back an empty string to `ssl_support_method` unless the `acm_certificate_arn` variable is set with a certificate ARN. This same behavior is continued in every version up to `0.81.0` which just gives a static value of `sni-only`.

## Fix
With my findings simply updating the module source version to `0.81.0` is sufficient to make the tutorial component functional again.

**Comment by osterman** [comment]
I think this error actually related to this comment: 
https://github.com/cloudposse/terraform-aws-cloudfront-s3-cdn/pull/207#issuecomment-1009958645

**Comment by jbouse** [comment]
yes, that looks correct. The AWS provider no longer accepts an empty value for `ssl_support_method`.
