### ISSUE TITLE
Metaweather API is unstable - May Cause Atmos Tutorials to fail

### ISSUE THREAD

**Issue by gmaentz** [cloudposse/tutorials#12]
## Describe the Bug
The atmos tutorial utilizes the metaweather api (http://www.metaweather.com/) in the fetch-weather component.  This API appears unstable and is often unavailable which causes this data fetch to error.

```hcl
locals {
  location_url = "https://www.metaweather.com/api/location/search/?lattlong=${local.lat},${local.lon}"
}

data "http" "fetch_location" {
  url = local.location_url

  request_headers = {
    Accept = "application/json"
  }
}
```

```bash
Error: HTTP request error. Response code: 404

  on main.tf line 33, in data "http" "fetch_location":
  33: data "http" "fetch_location" {


Error: 1 error occurred:
        * step "deploy plan": job "terraform plan": 1 error occurred:
        * step "plan cmd": job "terraform subcommand": command "terraform plan -out example-fetch-weather.planfile -var-file example-fetch-weather.terraform.tfvars.json" in "./components/terraform/fetch-weather": exit status 1
```

## Expected Behavior
Ideally this API would be available

## Steps to Reproduce
```bash
atmos terraform deploy fetch-weather -s example
```

## Additional Context
It may be valuable to change out the tutorials to not rely on this rather unreliable service.

**Comment by milldr** [comment]
Yes, that API is no longer available. We've updated the example with a different, working weather API

See https://github.com/cloudposse/tutorials/pull/13
